# Generated by Django 4.1.2 on 2022-10-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.FileField(upload_to='document/'),
        ),
    ]
