# Generated by Django 4.1.2 on 2022-10-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videoblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='videoblog/')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.FileField(upload_to='document/')),
            ],
        ),
    ]
