# Generated by Django 4.1.2 on 2022-10-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_marketingfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingfeature',
            name='image',
            field=models.FileField(upload_to='document/'),
        ),
    ]
