# Generated by Django 4.1.2 on 2022-10-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/')),
                ('title', models.CharField(choices=[('Blog post', 'Blog post'), ('Webinar', 'Webinar'), ('Report', 'Report')], default='Webinar', max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
